// UNITS IN REM
export const typescale = {
	displayLarge: {
		fontFamily: "Roboto",
		fontSize: 3.563,
		lineHeight: 4,
		fontWeight: 400,
		letterSpacing: -0.016,
	},
	displayMedium: {
		fontFamily: "Roboto",
		fontSize: 2.813,
		fontWeight: 400,
		lineHeight: 3.375,
		letterSpacing: 0,
	},
	displaySmall: {
		fontFamily: "Roboto",
		fontSize: 2.25,
		lineHeight: 2.75,
		fontWeight: 400,
		letterSpacing: 0,
	},
	headlineLarge: {
		fontFamily: "Roboto",
		fontSize: 2,
		lineHeight: 2.5,
		fontWeight: 400,
		letterSpacing: 0,
	},
	headlineMedium: {
		fontFamily: "Roboto",
		fontSize: 1.75,
		lineHeight: 2.25,
		fontWeight: 400,
		letterSpacing: 0,
	},
	headlineSmall: {
		fontFamily: "Roboto",
		fontSize: 1.5,
		lineHeight: 2,
		fontWeight: 400,
		letterSpacing: 0,
	},
	titleLarge: {
		fontFamily: "Roboto",
		fontSize: 1.375,
		lineHeight: 1.75,
		fontWeight: 500,
		letterSpacing: 0,
	},
	titleMedium: {
		fontFamily: "Roboto",
		fontSize: 1,
		lineHeight: 1.5,
		fontWeight: 500,
		letterSpacing: 0.009,
	},
	titleSmall: {
		fontFamily: "Roboto",
		fontSize: 0.875,
		lineHeight: 1.25,
		fontWeight: 500,
		letterSpacing: 0.006,
	},
	labelLarge: {
		fontFamily: "Roboto",
		fontSize: 0.875,
		lineHeight: 1.25,
		fontWeight: 500,
		letterSpacing: 0.006,
	},
	labelMedium: {
		fontFamily: "Roboto",
		fontSize: 0.75,
		lineHeight: 1,
		fontWeight: 500,
		letterSpacing: 0.031,
	},
	labelSmall: {
		fontFamily: "Roboto",
		fontSize: 0.688,
		lineHeight: 1,
		fontWeight: 500,
		letterSpacing: 0.031,
	},
	bodyLarge: {
		fontFamily: "Roboto",
		fontSize: 1,
		lineHeight: 1.5,
		fontWeight: 400,
		letterSpacing: 0.009,
	},
	bodyMedium: {
		fontFamily: "Roboto",
		fontSize: 0.875,
		lineHeight: 1.25,
		fontWeight: 400,
		letterSpacing: 0.016,
	},
	bodySmall: {
		fontFamily: "Roboto",
		fontSize: 0.75,
		lineHeight: 1,
		fontWeight: 400,
		letterSpacing: 0.031,
	},
};

/*
// UNITS IN PX
export const typescale = {
	displayLarge: {
		fontSize: 57,
		lineHeight: 64,
		fontWeight: 400,
		letterSpacing: -0.25,
	},
	displayMedium: {
		fontSize: 45,
		fontWeight: 400,
		lineHeight: 54,
		letterSpacing: 0,
	},
	displaySmall: {
		fontSize: 36,
		lineHeight: 44,
		fontWeight: 400,
		letterSpacing: 0,
	},
	headlineLarge: {
		fontSize: 32,
		lineHeight: 40,
		fontWeight: 400,
		letterSpacing: 0,
	},
	headlineMedium: {
		fontSize: 28,
		lineHeight: 36,
		fontWeight: 400,
		letterSpacing: 0,
	},
	headlineSmall: {
		fontSize: 24,
		lineHeight: 32,
		fontWeight: 400,
		letterSpacing: 0,
	},
	titleLarge: {
		fontSize: 22,
		lineHeight: 28,
		fontWeight: 500,
		letterSpacing: 0,
	},
	titleMedium: {
		fontSize: 16,
		lineHeight: 24,
		fontWeight: 500,
		letterSpacing: 0.15,
	},
	titleSmall: {
		fontSize: 14,
		lineHeight: 20,
		fontWeight: 500,
		letterSpacing: 0.1,
	},
	labelLarge: {
		fontSize: 14,
		lineHeight: 20,
		fontWeight: 500,
		letterSpacing: 0.1,
	},
	labelMedium: {
		fontSize: 12,
		lineHeight: 16,
		fontWeight: 500,
		letterSpacing: 0.5,
	},
	labelSmall: {
		fontSize: 11,
		lineHeight: 16,
		fontWeight: 500,
		letterSpacing: 0.5,
	},
	bodyLarge: {
		fontSize: 16,
		lineHeight: 24,
		fontWeight: 400,
		letterSpacing: 0.15,
	},
	bodyMedium: {
		fontSize: 14,
		lineHeight: 20,
		fontWeight: 400,
		letterSpacing: 0.25,
	},
	bodySmall: {
		fontSize: 12,
		lineHeight: 16,
		fontWeight: 400,
		letterSpacing: 0.5,
	},
};
 */
